[package]
name = "app-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.79"
winit = "0.26.1"

[dependencies.web-sys]
version = "0.3.56"
features = [
]
