version: "3.8"

services:
  app-web:
    image: node:17.5.0
    ports:
      - "8080:8080"
    volumes:
      - ${APP_WEB_DIR}:/app
    working_dir: /app
    command: yarn run serve
    container_name: app-web
